// flow-typed signature: 1b3c182de39ad5e1747ac76046c323fd
// flow-typed version: <<STUB>>/atom.storage_v^0.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom.storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom.storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom.storage/lib/atom.storage' {
  declare module.exports: any;
}

declare module 'atom.storage/src/atom.storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom.storage/lib/atom.storage.js' {
  declare module.exports: $Exports<'atom.storage/lib/atom.storage'>;
}
declare module 'atom.storage/src/atom.storage.js' {
  declare module.exports: $Exports<'atom.storage/src/atom.storage'>;
}
