// flow-typed signature: 00a6c48749843892c47c0b075ece5d51
// flow-typed version: <<STUB>>/karet_v^0.2.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karet/lib/karet' {
  declare module.exports: any;
}

declare module 'karet/src/karet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karet/lib/karet.js' {
  declare module.exports: $Exports<'karet/lib/karet'>;
}
declare module 'karet/src/karet.js' {
  declare module.exports: $Exports<'karet/src/karet'>;
}
