// flow-typed signature: 6cf52a9289452980d172ebfb89d66cf8
// flow-typed version: <<STUB>>/karet.util_v^0.11.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karet.util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karet.util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karet.util/lib/karet.util' {
  declare module.exports: any;
}

declare module 'karet.util/src/karet.util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karet.util/lib/karet.util.js' {
  declare module.exports: $Exports<'karet.util/lib/karet.util'>;
}
declare module 'karet.util/src/karet.util.js' {
  declare module.exports: $Exports<'karet.util/src/karet.util'>;
}
