// flow-typed signature: 72dce3fe18aaac8c20c58e67527d89d0
// flow-typed version: <<STUB>>/kefir.combines_v^4.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kefir.combines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kefir.combines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kefir.combines/dist/kefir.combines' {
  declare module.exports: any;
}

declare module 'kefir.combines/dist/kefir.combines.min' {
  declare module.exports: any;
}

declare module 'kefir.combines/lib/kefir.combines' {
  declare module.exports: any;
}

declare module 'kefir.combines/src/kefir.combines' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kefir.combines/dist/kefir.combines.js' {
  declare module.exports: $Exports<'kefir.combines/dist/kefir.combines'>;
}
declare module 'kefir.combines/dist/kefir.combines.min.js' {
  declare module.exports: $Exports<'kefir.combines/dist/kefir.combines.min'>;
}
declare module 'kefir.combines/lib/kefir.combines.js' {
  declare module.exports: $Exports<'kefir.combines/lib/kefir.combines'>;
}
declare module 'kefir.combines/src/kefir.combines.js' {
  declare module.exports: $Exports<'kefir.combines/src/kefir.combines'>;
}
