// flow-typed signature: e3d5ec6540c3b85646fe145518c633fa
// flow-typed version: <<STUB>>/kefir.atom_v^5.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kefir.atom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kefir.atom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kefir.atom/dist/kefir.atom' {
  declare module.exports: any;
}

declare module 'kefir.atom/dist/kefir.atom.min' {
  declare module.exports: any;
}

declare module 'kefir.atom/lib/kefir.atom' {
  declare module.exports: any;
}

declare module 'kefir.atom/src/kefir.atom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kefir.atom/dist/kefir.atom.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom'>;
}
declare module 'kefir.atom/dist/kefir.atom.min.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom.min'>;
}
declare module 'kefir.atom/lib/kefir.atom.js' {
  declare module.exports: $Exports<'kefir.atom/lib/kefir.atom'>;
}
declare module 'kefir.atom/src/kefir.atom.js' {
  declare module.exports: $Exports<'kefir.atom/src/kefir.atom'>;
}
