// flow-typed signature: 9a9937ebf30728e6a3342dead08ee4d1
// flow-typed version: <<STUB>>/partial.lenses_v^8.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'partial.lenses'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'partial.lenses' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'partial.lenses/dist/partial.lenses' {
  declare module.exports: any;
}

declare module 'partial.lenses/dist/partial.lenses.min' {
  declare module.exports: any;
}

declare module 'partial.lenses/lib/partial.lenses' {
  declare module.exports: any;
}

declare module 'partial.lenses/src/partial.lenses' {
  declare module.exports: any;
}

// Filename aliases
declare module 'partial.lenses/dist/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses'>;
}
declare module 'partial.lenses/dist/partial.lenses.min.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses.min'>;
}
declare module 'partial.lenses/lib/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/lib/partial.lenses'>;
}
declare module 'partial.lenses/src/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/src/partial.lenses'>;
}
